### ISSUE TITLE
How can I import athletes into special-named weight categories from excel?

### ISSUE THREAD

**Issue by futaz** [unitedworldwrestling/arena-public#80]
Hey!

We are using Arena version 1.5.78.1.
We have custom audiences and custom weight categories configured in the custom config menu and there are some weight categories like the second one below:
```
cadets:
    fs:
        110kg:
            identifier: 110kg
            name: '110 kg'
            minWeight: 93
            maxWeight: 110
            roundsNumber: 2
            roundDuration: 120
            averageDuration: 420
        110pkg:
            identifier: 110pkg
            name: '+110 kg'
            minWeight: 111
            maxWeight: 130
            roundsNumber: 2
            roundDuration: 120
            averageDuration: 420
```

I know we should call the second one 130kg instead but our client use Arena this way, so... I'm here to find a solution to our problem.

I'd like to import athletes from excel for an event. I've created an xlsx file based on the downloadable import-athletes.xlsx. It's working fine until I have an athlete with a special, +110 kg weight category. Arena shows an error for each row of this kind:

> Skipped line 2: The Weight Category cannot be found (cadets -> fs -> +110 kg).

I've tried to put the identifier `"110pkg"`, the name without the kg suffix `"+110"` and the name `"+110 kg"` into the Weight Category column in the spreadsheet, but neither worked.

Can I somehow solve this problem?

Thanks!
